import logging
import json
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from livekit.agents import (
    Agent,
    AgentSession,
    JobContext,
    JobProcess,
    RoomInputOptions,
    WorkerOptions,
    cli,
    metrics,
    tokenize,
    function_tool,
    RunContext,
    MetricsCollectedEvent,
)
from livekit.plugins import murf, silero, google, deepgram, noise_cancellation
from livekit.plugins.turn_detector.multilingual import MultilingualModel

logger = logging.getLogger("wellnessAgent")

load_dotenv(".env.local")

# -------------------------------------------------------------------
# JSON LOG FILE (single file for all check-ins)
# -------------------------------------------------------------------
LOG_FILE = Path(__file__).parent / "wellness_log.json"


def load_wellness_history():
    """Load the full wellness log as a list."""
    if not LOG_FILE.exists():
        return []
    try:
        with open(LOG_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
            if isinstance(data, list):
                return data
            return []
    except Exception as e:
        logger.error(f"Failed to read wellness_log.json: {e}")
        return []


def get_last_entry():
    history = load_wellness_history()
    if not history:
        return None
    return history[-1]


# -------------------------------------------------------------------
# TOOL: save_checkin
# The LLM will call this once each session when the recap is done.
# -------------------------------------------------------------------
@function_tool
async def save_checkin(
    context: RunContext,
    mood: str,
    energy: str,
    stresses: list[str],
    goals: list[str],
    selfcare: list[str],
    summary: str,
):
    """
    Save a single daily wellness check-in to wellness_log.json.

    Args:
      mood: User's self-reported mood for the day (free text).
      energy: User's self-reported energy (e.g. '3/10' or 'low/medium/high').
      stresses: Things currently stressing the user (list of strings).
      goals: 1–3 main intentions / objectives for the day.
      selfcare: Things they want to do for themselves (rest, exercise, hobbies).
      summary: A short, neutral, supportive summary sentence generated by you.
    """

    entry = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "mood": mood,
        "energy": energy,
        "stresses": stresses,
        "goals": goals,
        "selfcare": selfcare,
        "summary": summary,
    }

    history = load_wellness_history()
    history.append(entry)

    try:
        with open(LOG_FILE, "w", encoding="utf-8") as f:
            json.dump(history, f, indent=2)

        logger.info(f"Saved wellness check-in to {LOG_FILE}")
        print(f"DEBUG >>> saved wellness check-in to: {LOG_FILE}")

        return {
            "status": "saved",
            "file": str(LOG_FILE),
            "entry": entry,
            "total_entries": len(history),
        }
    except Exception as e:
        logger.error(f"Failed to save wellness check-in: {e}")
        return {"status": "error", "error": str(e)}


# -------------------------------------------------------------------
# BUILD WELLNESS AGENT
# -------------------------------------------------------------------
def create_wellness_agent() -> Agent:
    last = get_last_entry()

    if last:
        last_goals = last.get("goals") or []
        goals_text = ", ".join(last_goals) if last_goals else "no specific goals listed"
        last_context = (
            f"Last check-in was on {last.get('timestamp', 'an unknown date')} "
            f"with mood '{last.get('mood', 'unknown')}' and energy '{last.get('energy', 'unknown')}'. "
            f"The main goals then were: {goals_text}."
        )
    else:
        last_context = (
            "There is no previous check-in yet. "
            "Treat this as the user's first wellness conversation with you."
        )

    instructions = f"""
    You are a calm, grounded Health & Wellness Voice Companion from Cult.fit

    You are supportive, realistic, and non-clinical.
    You are NOT a doctor, therapist, or clinician.
    You must NOT diagnose, label conditions, or give medical advice.
    Stay practical, gentle, and focused on small daily actions.

    Context about past check-ins:
    {last_context}

    Your job each session:
    1) Start with a brief, friendly greeting.
       If there is past data, gently reference it.
       Example: "Last time we talked, you mentioned low energy.
       How does today compare?"

    2) Ask about mood and energy for today.
       - Examples:
         - "How are you feeling today emotionally?"
         - "What's your energy like — low, medium, or high?"
         - "Anything stressing you out right now?"

    3) Ask about intentions / objectives for the day.
       - Ask for 1–3 simple, practical goals.
       - Ask if there's anything they want to do for themselves:
         rest, exercise, hobbies, time off screens, etc.

    4) Offer simple, realistic advice or reflections.
       - Suggestions MUST be:
         - small, actionable, everyday things
         - non-medical, non-diagnostic
       - Good examples:
         - breaking big goals into tiny steps
         - taking a 5–10 minute walk or stretch
         - scheduling a short break between tasks
       - Avoid medical claims or telling the user what condition they may have.

    5) Close with a brief recap.
       - Summarize:
         - today's mood (short phrase)
         - energy
         - main 1–3 goals
         - one simple self-care intention
       - Ask: "Does this sound right for today?"

    6) Once the user confirms the recap:
       - Call the `save_checkin` tool EXACTLY ONCE.
         Pass:
           mood: your best concise description of their mood
           energy: their self-described energy
           stresses: a short list of key stressors
           goals: their main 1–3 goals
           selfcare: any self-care intentions
           summary: your single-sentence neutral summary
       - After the tool returns, briefly acknowledge that
         today's check-in has been saved.

    Tone:
    - Warm but not overly cheerful when the user is struggling.
    - Empathetic, practical, grounded.
    - Avoid emojis and fancy formatting.
    """

    return Agent(
        instructions=instructions,
        tools=[save_checkin],
    )


# -------------------------------------------------------------------
# PREWARM
# -------------------------------------------------------------------
def prewarm(proc: JobProcess):
    proc.userdata["vad"] = silero.VAD.load()


# -------------------------------------------------------------------
# ENTRYPOINT
# -------------------------------------------------------------------
async def entrypoint(ctx: JobContext):
    ctx.log_context_fields = {"room": ctx.room.name}

    session = AgentSession(
        stt=deepgram.STT(model="nova-3"),
        llm=google.LLM(model="gemini-2.5-flash"),
        tts=murf.TTS(
            voice="en-US-matthew",
            style="Conversation",
            tokenizer=tokenize.basic.SentenceTokenizer(min_sentence_len=2),
            text_pacing=True,
        ),
        turn_detection=MultilingualModel(),
        vad=ctx.proc.userdata["vad"],
        preemptive_generation=True,
    )

    usage_collector = metrics.UsageCollector()

    @session.on("metrics_collected")
    def _on_metrics(ev: MetricsCollectedEvent):
        metrics.log_metrics(ev.metrics)
        usage_collector.collect(ev.metrics)

    async def log_usage():
        summary = usage_collector.get_summary()
        logger.info(f"Usage: {summary}")

    ctx.add_shutdown_callback(log_usage)

    await session.start(
        agent=create_wellness_agent(),
        room=ctx.room,
        room_input_options=RoomInputOptions(
            noise_cancellation=noise_cancellation.BVC(),
        ),
    )

    await ctx.connect()


if __name__ == "__main__":
    cli.run_app(
        WorkerOptions(
            entrypoint_fnc=entrypoint,
            prewarm_fnc=prewarm,
        )
    )
